name: chatgpt

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 14400
    runs-on: ubuntu-22.04
    
    steps:
    - name: cloudflare
      run: |
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && sudo dpkg -i cloudflared.deb && sudo cloudflared service install eyJhIjoiMWE1MTc4MTE0YTZjOWZmNDllMzZiNmMxNzVlOTZiYjkiLCJ0IjoiNzJhYzg0MmYtZmYxMy00YTEwLWI3NGYtYTY3MWQyYTlhZWZkIiwicyI6Ik9HTTVPV1l5WlRJdFlqQTNPUzAwWkRCa0xXSmlaVEl0WVRjME5UWXpNalpoTlRnNSJ9

    - name: docker start
      run: |
        docker pull hlohaus789/g4f
        docker run -p 8080:8080 -p 1337:1337 -p 7900:7900 --shm-size="2g" -v ${PWD}/har_and_cookies:/app/har_and_cookies -v ${PWD}/generated_images:/app/generated_images hlohaus789/g4f:latest
