name: sshx

on: [push, workflow_dispatch]

jobs:
  build:
    timeout-minutes: 14400
    runs-on: ubuntu-22.04
    
    steps:
    - name: install
      run: |
        sudo apt install curl -y
        curl -sSf https://sshx.io/get | sh
        
    - name: sshx start
      run: |
        sshx
